services:
  nginx:
    container_name: nginx
    image: nginx:custom_nginx
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - www:/var/www/html
        #restart: unless-stopped

volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /home/graux/data/www
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/graux/data/database
      o: bind

networks:
  inception_network:
    name: inception_network
