#version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - "443:443"

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
          #volumes:
          #- www:/var/www/html
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
      #volumes:
      #- database:/var/lib/mysql
    networks:
      - inception

volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WWW_PATH}
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATABASE_PATH}
      o: bind

networks:
  inception:
    name: inception
