services:
  nginx:
    container_name: nginx
    image: nginx:custom
    build: requirements/nginx
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - www:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:custom
    env_file: .env
    build:
      context: requirements/mariadb
      args:
        - MYSQL_DB=${MYSQL_DB}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_USER_PASS=${MYSQL_USER_PASS}
        - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    networks:
      - inception_network
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    image: wordpress:custom
    build: requirements/wordpress
    env_file: .env
    networks:
      - inception_network
    volumes:
      - www:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /home/graux/data/www
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/graux/data/database
      o: bind

networks:
  inception_network:
    name: inception_network
